apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dns
  labels:
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/env: dev
    app.kubernetes.io/tier: backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/stage: dev
    app.kubernetes.io/webapp-subdomain-name: gotest
    app.kubernetes.io/package: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dns-test
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dns-test
    spec:
      containers:
      - name: dns-test
        image: "popopame/ovh_dns_record_creation:latest"
        command: ["sleep","3600"]
        volumeMounts:
        - name: configuration-file
          mountPath: "/root"
      volumes:
      - name: configuration-file
        secret:
          secretName: configuration-file
          items:
          - key: configuration-file
            path: .ovh.conf

